language: generic

dist: trusty
sudo: false
# Get latest install-jdk.sh script
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
matrix:
  include:
# Java 11 "Oracle JDK"
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
# Java 11 "OpenJDK"
    - env: JDK='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
before_script:
  - wget http://services.gradle.org/distributions/gradle-4.10-bin.zip
  - unzip gradle-4.10-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.10
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)

