language: java
jdk:
  - oraclejdk11
dist: trusty
sudo: false
before_install:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
  - wget http://services.gradle.org/distributions/gradle-4.10-bin.zip
  - unzip gradle-4.10-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.10
  - export PATH=$GRADLE_HOME/bin:$PATH
matrix:
  include:
    - env: JDK='Oracle JDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
script:
  - gradle jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
